#!/bin/bash
# Quick Reference: Temperature API Docker Deployment
# Date: 8 March 2026

echo "═══════════════════════════════════════════════════════════════════"
echo "             TEMPERATURE API - DOCKER QUICK REFERENCE"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Check if containers are running
echo "📊 CONTAINER STATUS:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep temperature

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "                         API ENDPOINTS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🔴 DIRECT INSTANCES:"
echo "  • API 1 (Port 5000): http://localhost:5000"
echo "  • API 2 (Port 5001): http://localhost:5001"
echo ""
echo "🟢 VIA LOAD BALANCER (NGINX):"
echo "  • HTTP:  http://localhost:80"
echo "  • HTTPS: https://localhost:443"
echo ""
echo "📊 MONITORING:"
echo "  • Metrics: http://localhost:5000/metrics"
echo "  • Health:  http://localhost:5000/health"
echo "  • Swagger: http://localhost:5000/swagger"
echo ""
echo "🗄️  DATABASES:"
echo "  • PostgreSQL: localhost:54320 (user: postgres)"
echo "  • Redis:      localhost:6379"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "                      USEFUL COMMANDS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "View logs (live):"
echo "  docker logs temperature-api-1 -f"
echo ""
echo "View logs (all containers):"
echo "  docker logs temperature-api-postgres -f"
echo "  docker logs temperature-api-redis -f"
echo ""
echo "Stop all services:"
echo "  cd TemperatureApi/Deployment"
echo "  docker-compose -f docker-compose-dev.yml down"
echo ""
echo "Restart services:"
echo "  docker-compose -f docker-compose-dev.yml restart"
echo ""
echo "Test API:"
echo "  curl http://localhost:5000/metrics | head -20"
echo ""
echo "View all containers:"
echo "  docker ps -a"
echo ""
echo "Delete all containers and volumes:"
echo "  docker-compose -f docker-compose-dev.yml down -v"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "                    CONFIGURATION DETAILS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Environment Variables (from .env):"
echo "  JWT_KEY=${JWT_KEY:0:20}... ($(echo -n "$JWT_KEY" | wc -c) chars)"
echo "  POSTGRES_PASSWORD: ****"
echo "  ALLOWED_ORIGINS: http://localhost:*"
echo ""
echo "Docker Compose File:"
echo "  TemperatureApi/Deployment/docker-compose-dev.yml"
echo ""
echo "Build Directory:"
echo "  $(pwd)/TemperatureApi"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "                      TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "If services won't start:"
echo "  1. Check logs: docker logs temperature-api-1"
echo "  2. Verify ports are free: lsof -i :5000"
echo "  3. Clean up: docker-compose -f docker-compose-dev.yml down -v"
echo "  4. Restart: docker-compose -f docker-compose-dev.yml up -d"
echo ""
echo "If health checks are failing:"
echo "  1. Wait 30+ seconds for services to fully start"
echo "  2. Check if database is accessible"
echo "  3. View detailed logs: docker logs temperature-api-1"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "✅ YOUR API IS RUNNING IN DOCKER!"
echo "═══════════════════════════════════════════════════════════════════"
